### ISSUE TITLE
copy/move to an existing dir failed for object storage services

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-integration-test#39]
In [GSP-134: Write Behavior Consistency](https://github.com/beyondstorage/go-storage/blob/master/docs/rfcs/134-write-behavior-consistency.md), we have an agreement to return `ErrObjectModeInvalid` when the dst path is a dir in write operations. Also we added `copy/move to an existing dir` in https://github.com/beyondstorage/go-integration-test/pull/32 to check the error handling.

For object storage, we add `/` at the end of path to simulate a directory. With the constraint that `path` should not end with `/` in services, seems that `dst` will not identify a directory for `Move(src, dst)/Copy(src, dst)`.

After `CreateDir("dstPath")`,  the object `dstPath/` was created. Then `Copy("srcPath", "dstPath")` or `Move("srcPath", "dstPath")`, the `srcPath` will be copied or moved to the object `dstPath`. As most of the object storage services have native support for overwirte,  `copy/move` will succeed instead of returning `ErrObjectModeInvalid`.

**Comment by JinnyYi** [comment]
From the current implementation, only file copy or move is supported. Even empty directories are not supportd(Maybe we should modify the descriptions for `Copy` and `Move` in `go-storage`). 
For object storage services,  can we draw a conclusion that `copy/move a object to a dir` will not happend under the current constraint and we can skip the test case directly?

**Comment by Xuanwo** [comment]
I think it's related to https://github.com/beyondstorage/go-storage/issues/683

**Comment by JinnyYi** [comment]
> I think it's related to [beyondstorage/go-storage#683](https://github.com/beyondstorage/go-storage/issues/683)

I'm not sure if I can split `TestCopier` function into two functions like `TestCopierNative` and `TestCopierVirtual`. Or we can add another function like `TestCopierBasic`  as `native` and `virtual` have duplicate test cases?

**Comment by Xuanwo** [comment]
> Or we can add another function like `TestCopierBasic` as `native` and `virtual` have duplicate test cases?

Looks good to me.

~~Maybe we can have `TestCopier` and `TestCopierWithVirtualDir`?~~

 I found that this is actually a feature interdependency problem.

Towards a service, a feature could be in the following states: 

1. not implemented
1. implement with virtual support (needs to be enabled via feature flags)
1. implement with native support

For cases 1&3, it's simple to define the behavior. But for case 2, there could be some limitations for their behavior, so we have to loosen the restriction for them.

More complicated, our features could depend on each other.

For example, `copy` behavior could be affected by `dir` support:

- If dir is not supported, copy from `a` to `b/` is OK and valid
- If dir is supported, copy from `a` to `b/` is not allowed.

So I think the case of our test should be organized into feature groups instead of interfaces.

For example, `TestCopier` should be split into:

- TestCopier: basic tests for copier, only the most normal path.
- TestCopierWithDir: native dir tests for copier (require both Copier and native dir support)
- TestCopierWithVirtualDir: virtual dir test for copier (allows some loosen tests for dir?)
